batch_ingestion:
   - product
   - customer
   - transaction

datamart:
   - resources/sql/silver/dim_customer.sql
   - resources/sql/silver/dim_product.sql
   - resources/sql/silver/fact_transaction.sql